### ISSUE TITLE
OTP 29 compile fails because memento 0.5 redefines built-in record/0 type

### ISSUE THREAD

**Issue by mikehostetler** [agentjido/jido_signal#164]
Reported by: `jaicool`

## Summary

`jido_signal` currently depends directly on `memento ~> 0.5.0`, and `memento 0.5.0` does not compile under OTP 29 / Elixir 1.19.5.

Current direct dependency in this repo:

```elixir
{:memento, "~> 0.5.0"}
```

## Failure

```text
==> memento
Compiling 13 files (.ex)

== Compilation error in file lib/memento/table/table.ex ==
** (Kernel.TypespecError) lib/memento/table/table.ex:85: type record/0 is a built-in type and it cannot be redefined
    (elixir 1.19.5) lib/kernel/typespec.ex:992: Kernel.Typespec.compile_error/2
    (stdlib 8.0) lists.erl:2470: :lists.foldl_1/3
    (elixir 1.19.5) lib/kernel/typespec.ex:230: Kernel.Typespec.translate_typespecs_for_module/2
could not compile dependency :memento, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile memento --force", update it with "mix deps.update memento" or clean it with "mix deps.clean memento"
```

## Impact

Any project depending on `jido_signal` can fail to compile on OTP 29 because `memento 0.5.0` redefines `record/0`, which is now rejected as a built-in typespec name.

## Suggested follow-up

- Reproduce under OTP 29 / Elixir 1.19.5.
- Check whether a compatible `memento` release exists or whether this dependency needs to be patched/replaced.
- After fixing, release a compatible `jido_signal` version so downstream `jido` users can update.
